# https://github.com/marketplace/actions/publish-docker

name: Publish Docker Images

on: push

jobs:
  webpage-title:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: atton/webpage-title
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: webpage-title/Dockerfile
        buildoptions: "--compress --force-rm --pull"
        context: webpage-title
